---
title: "Homework 1"
author: "Jessie Merrifield"
date: 2023-09-23
output: github_document
---

# Problem 1

Starting out with loading library and data

```{r, message=FALSE}
library(moderndive)
library(tidyverse)

data("early_january_weather")
```


describing the data with a summary, the number of rows, the number of columns, and the mean of the variable "temp"

```{r descriptive}
summary(early_january_weather)

nrow(early_january_weather)

ncol(early_january_weather)

mean(early_january_weather$temp)
```

Scatterplot for time_hour and temp, color by variable humid 

```{r scatterplot}

P1_scatter<-ggplot(data = early_january_weather,
                   aes(x=time_hour, y=temp, color=humid))+
  geom_point()

ggsave("scatter_plot_P1.pdf", height = 4, width = 6)

print(P1_scatter)

```


There seems to be an overall positive relationship between temp and time_hour. 

# Problem 2

Creating a dataframe

```{r}
P2_df = tibble(
  vec_numeric = rnorm(10),
  vec_char = c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10"),
  vec_logical = vec_numeric>0,
  vec_factor = factor(c("1", "1", "1", "2", "2", "2", "3", "3", "3","3"))
)

```


